apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-prod-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: 'https://github.com/rvaidhya4192/gitops-cert-level-3-examples.git'
        revision: HEAD
        directories:
          - path: argocd-apps-structure/apps/*/envs/prod-us
          - path: argocd-apps-structure/apps/*/envs/prod-eu
  template:
    metadata:
      name: '{{index .path.segments 2}}-{{index .path.segments 4}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/rvaidhya4192/gitops-cert-level-3-examples.git'
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        name: cluster-2
        namespace: '{{index .path.segments 2}}-{{index .path.segments 4}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true

